# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5843d5229e4be1bcc114e32355c59d39"
name = "qwikcilver-apps"
handle = "qwikcilver-apps"
application_url = "https://shopify-qwikcilver.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-dfc26f2b.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://shopify-qwikcilver.onrender.com/auth/callback",
  "https://shopify-qwikcilver.onrender.com/auth/shopify/callback",
  "https://shopify-qwikcilver.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
